title: Ecliptica
email: contact@quasarapp.com
description: >-
  Ecliptica is a first-person open-world colony survival simulator with a fully dynamic economy.
baseurl: "/EclipticaPage" # the subpath of your site, e.g. /blog
url: "https://quasarapp.github.io" # the base hostname & protocol for your site
twitter_username: quasarapp
github_username:  quasarapp

# Build settings
theme: minima # We'll override most of it, but let's keep a base
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
